apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: project
          image: project-app:1.12
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
