apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: the-project:2.06
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: the-project-config
