apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: broadcaster:v1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              value: "nats://nats-svc.default.svc:4222"
            - name: WEBHOOK_URL
              value: ""
