apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: log-output-configmap
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-output
          image: log-output:2.05
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
