apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: log-writer
          image: log-writer:1.0
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
        - name: log-reader
          image: log-reader:1.1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
