apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-project-ingress
spec:
  rules:
  - http:
      paths:
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todo-backend-svc
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: the-project-svc
            port:
              number: 8080
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-wikipedia-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: random-wiki-todo
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  WIKI_URL=$(curl -s -I -L -w "%{url_effective}" -o /dev/null https://en.wikipedia.org/wiki/Special:Random)
                  TODO_TEXT="Read $WIKI_URL"
                  curl -X POST http://todo-backend-svc:5000/todos \
                    -H "Content-Type: application/json" \
                    -d "{\"todo\":\"$TODO_TEXT\"}"
