apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress-and-cronjob.yaml

images:
  - name: todo-backend-image
    newName: todo-backend
    newTag: latest
  - name: the-project-image
    newName: the-project
    newTag: latest
